### ISSUE TITLE
front end 

### ISSUE THREAD

**Issue by shviam-2018** [shviam-2018/eva#1]
I need someone to create a front end that has a UI that has a circular button that needs to be hold down andtalkedkreleasee to send

**Comment by MCKH03** [comment]
I can create the UI you need but I actually didn't understand how should the button be and didn't understand the last part of your issue

**Comment by Harshvartak** [comment]
What sort of Frontend do you need?
Any language preferences?
Any UI type preference?
If none, you could try ReactJS [react-recorder](https://github.com/SarfarazAhmed1012/recorder-react/tree/main/) as an example

**Comment by shviam-2018** [comment]
yes, I would like a GUI in HTML. anything that looks like a Google Assistant app a button that is pushed to talk 

> What sort of Frontend do you need? Any language preferences? Any UI type preference? If none, you could try ReactJS [react-recorder](https://github.com/SarfarazAhmed1012/recorder-react/tree/main/) as an example


yes, I would like a GUI in HTML. anything that looks like a Google Assistant app a button that is pushed to talk assigned

**Comment by shviam-2018** [comment]
add me on Discord:https://discordapp.com/users/1113472905523777657
